
on:
  pull_request:
    branches: [ master, development ] 

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [
          aarch64-linux-android, 
          aarch64-unknown-linux-gnu,
          # aarch64-unknown-linux-musl,
          # arm-linux-androideabi,
          # arm-unknown-linux-gnueabi,
          # armv7-unknown-linux-gnueabihf,
          # mips-unknown-linux-gnu,
          # mips64-unknown-linux-gnuabi64,
          # powerpc-unknown-linux-gnu,
          # powerpc64-unknown-linux-gnu,
          # riscv64gc-unknown-linux-gnu,
          # s390x-unknown-linux-gnu,
          # x86_64-unknown-freebsd,
          # x86_64-unknown-illumos,
          # x86_64-unknown-linux-musl,
          # x86_64-unknown-netbsd,
        ]
        feature: [kyber512, kyber768, kyber1024]
      
        include:
          - opt: 90s
    
    steps:
      - uses: actions/checkout@v3

      - name: rust-cargo
        uses: actions-rs/cargo@v1.0.1
        with:
          use-cross: true
          command: test
          args: --target ${{ matrix.target }} --features "${{ matrix.feature }} ${{ matrix.opt }}" 
