env: 
  RUSTFLAGS: "-Z sanitizer=address -C target-cpu=native -C target-feature=+aes,+avx2,+sse2,+sse4.1,+bmi2,+popcnt"
  RUSTDOCFLAGS: "-Z sanitizer=address"

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Rust Nightly
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly
          override: true

      - name: Install NASM Compiler
        run: sudo apt-get install -y nasm
        
      - name: Generate Known Answer Tests
        shell: bash
        working-directory: ./tests/KAT
        run: |
          chmod +x build_kats.sh
          bash build_kats.sh

      - name: Run Known Answer Tests
        shell: bash
        working-directory: ./tests
        run: |
          chmod +x run_all_tests.sh 
          KAT=1 AVX2=1 NASM=1 ./run_all_tests.sh